Momentum:
    train_steps: 1000
    use_dropout: true
    dropout_keep_probability: 0.8
    l2_regularizer_weight: 0.00004
    max_detections_per_class: 100
    batch_size: 512
    learning_rate_base: 0.008
    warmup_learning_rate: 0.0013
    momentum_optimizer_value: 0.9
Adam:
    num_classes: 1
    train_steps: 140000
    use_dropout: true
    dropout_keep_probability: 0.8
    l2_regularizer_weight: 0.00004
    initial_learning_rate: 0.001
    first_schedule_steps: 90000
    first_schedule_lr: 0.0001
    second_schedule_steps: 120000
    second_schedule_lr: 0.00001
    epsilon: 0.0000001
    batch_size : 10
