# This sample config contains all fields supported by ravenML core and the keypoints regression plugin.
# Plugin specific configuration is located in the plugin field.

dataset: tinycygnusdistractors_pt
overwrite_local: False
artifact_path: './artifacts'
ec2_policy: stop
metadata:
    created_by: Kevin Black
    comments: no thanks
plugin:
    keypoints: 20
    batch_size: 5
    learning_rate: 0.001
    shuffle_buffer_size: 10
    pnp_focal_length: 1422.2222222

