dataset: cygnus_interp_simulated2 
overwrite_local: False
ec2_policy: stop
metadata:
    created_by: Jacob Deutsch
    comments: no thanks
plugin:
    batch_size: 5
    epochs: 1
    cache_train_data: False
    comet: debug
    keypoints_path: keypoints.npy
    model_path: model.h5
    object_name: cygnus
    model_type: from_pose
    error_metric: keypoint_l2
    mask_mode: opengl_cut
    #cache: ./cullnet_cache # path to cullnet cache
    stl_path: Cygnus_ENHANCED.stl
    pnp_focal_length: 1422.2222222
    dropout: 0.0